version: '3.7'

services:
  logspout:
    image: lsnova/logspout-logstash:1.0.0
    restart: always
    environment:
      - ROUTE_URIS=multiline+logstash://logstash:5000
      - MULTILINE_MATCH=first
      - MULTILINE_PATTERN=^\d{4}-\d{2}-\d{2}
    links:
      - logstash
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    depends_on:
      - logstash

  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    restart: always
    volumes:
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./config/pipeline.conf:/usr/share/logstash/pipeline/pipeline.conf
      - ./logs:/tmp/logs
    environment:
      - LOGSPOUT=ignore

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    links:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - LOGSPOUT=ignore
    ports:
      - '5601:5601'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      - ES_JAVA_OPTS: "-Xms2048m -Xmx2048m"
      - discovery.type=single-node
      - LOGSPOUT=ignore
    ports:
      - '9200:9200'
      - '9300:9300'

